version: '3.8'

services:
  app:
    build: .
    networks:
      - webnet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
